"""ComfyUI registration shim.

Each node implementation lives in its own module. ComfyUI imports this file as
the package entry point, so keep it small and only expose mappings here.
"""

try:
    from .pid_decode import NODE_CLASS_MAPPINGS as DECODE_CLASS_MAPPINGS
    from .pid_decode import NODE_DISPLAY_NAME_MAPPINGS as DECODE_DISPLAY_NAME_MAPPINGS
    from .pid_text_prompt import NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS
    from .pid_text_prompt import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_NAME_MAPPINGS
    from .pid_ksampler_capture import NODE_CLASS_MAPPINGS as CAPTURE_CLASS_MAPPINGS
    from .pid_ksampler_capture import NODE_DISPLAY_NAME_MAPPINGS as CAPTURE_DISPLAY_NAME_MAPPINGS
    from .pid_prepare import NODE_CLASS_MAPPINGS as PREPARE_CLASS_MAPPINGS
    from .pid_prepare import NODE_DISPLAY_NAME_MAPPINGS as PREPARE_DISPLAY_NAME_MAPPINGS
    from .pid_sample import NODE_CLASS_MAPPINGS as SAMPLE_CLASS_MAPPINGS
    from .pid_sample import NODE_DISPLAY_NAME_MAPPINGS as SAMPLE_DISPLAY_NAME_MAPPINGS
    from .pid_finalize import NODE_CLASS_MAPPINGS as FINALIZE_CLASS_MAPPINGS
    from .pid_finalize import NODE_DISPLAY_NAME_MAPPINGS as FINALIZE_DISPLAY_NAME_MAPPINGS
    from .pid_empty_latent import NODE_CLASS_MAPPINGS as EMPTY_LATENT_CLASS_MAPPINGS
    from .pid_empty_latent import NODE_DISPLAY_NAME_MAPPINGS as EMPTY_LATENT_DISPLAY_NAME_MAPPINGS
except ImportError:  # Allows `python -c "import nodes"` from this folder.
    from pid_decode import NODE_CLASS_MAPPINGS as DECODE_CLASS_MAPPINGS
    from pid_decode import NODE_DISPLAY_NAME_MAPPINGS as DECODE_DISPLAY_NAME_MAPPINGS
    from pid_text_prompt import NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS
    from pid_text_prompt import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_NAME_MAPPINGS
    from pid_ksampler_capture import NODE_CLASS_MAPPINGS as CAPTURE_CLASS_MAPPINGS
    from pid_ksampler_capture import NODE_DISPLAY_NAME_MAPPINGS as CAPTURE_DISPLAY_NAME_MAPPINGS
    from pid_prepare import NODE_CLASS_MAPPINGS as PREPARE_CLASS_MAPPINGS
    from pid_prepare import NODE_DISPLAY_NAME_MAPPINGS as PREPARE_DISPLAY_NAME_MAPPINGS
    from pid_sample import NODE_CLASS_MAPPINGS as SAMPLE_CLASS_MAPPINGS
    from pid_sample import NODE_DISPLAY_NAME_MAPPINGS as SAMPLE_DISPLAY_NAME_MAPPINGS
    from pid_finalize import NODE_CLASS_MAPPINGS as FINALIZE_CLASS_MAPPINGS
    from pid_finalize import NODE_DISPLAY_NAME_MAPPINGS as FINALIZE_DISPLAY_NAME_MAPPINGS
    from pid_empty_latent import NODE_CLASS_MAPPINGS as EMPTY_LATENT_CLASS_MAPPINGS
    from pid_empty_latent import NODE_DISPLAY_NAME_MAPPINGS as EMPTY_LATENT_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **DECODE_CLASS_MAPPINGS,
    **PROMPT_CLASS_MAPPINGS,
    **CAPTURE_CLASS_MAPPINGS,
    **PREPARE_CLASS_MAPPINGS,
    **SAMPLE_CLASS_MAPPINGS,
    **FINALIZE_CLASS_MAPPINGS,
    **EMPTY_LATENT_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **DECODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_DISPLAY_NAME_MAPPINGS,
    **CAPTURE_DISPLAY_NAME_MAPPINGS,
    **PREPARE_DISPLAY_NAME_MAPPINGS,
    **SAMPLE_DISPLAY_NAME_MAPPINGS,
    **FINALIZE_DISPLAY_NAME_MAPPINGS,
    **EMPTY_LATENT_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
